### ISSUE TITLE
Material UI update

### ISSUE THREAD

**Issue by SubhrajyotiSen** [SubhrajyotiSen/EmojiProject#1]
The app needs an UI overhaul according to Material Design guidelines

**Comment by ShreyaPrabhu** [comment]
I am taking this up :P

**Comment by mohitmanuja** [comment]
Hey, I am interested. But will you please tell me how it is working. For example, I am typing face after clicking on magic the same text is coming in "TO Emoji". What does it mean ?

No emoji is showing..

**Comment by SubhrajyotiSen** [comment]
@mohitmanuja I'm really sorry for the inconvenience. I will remove the hacktoberfest till the app is fixed

**Comment by SubhrajyotiSen** [comment]
In case anyone is still interest in taking this up, the translation has been fixed
